### PR TITLE
fails to build with text-1.1.0.0

### PR DESCRIPTION
**Pull request by mignon-p**
with text-1.1.0.0, I get:

```
src/Data/Hashabler.hs:1088:24:
    Not in scope: data constructor ‘T.Array’
    Perhaps you meant ‘P.Array’ (imported from Data.Primitive)
```

It appears that the first version of text to expose the Array constructor in Data.Text.Array is 1.1.1.3.  After adding this constraint, cabal grabs text-1.2.0.4 for me, and it builds fine.

### CODE REVIEW

**Comment by jberryman** [comment]
Thanks ppelleti!
